name: Process Recipes

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'

jobs:
  import_and_process:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: new-recipe-submissions-${{ github.run_id }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run import_from_form.py
        run: python _tools/import_from_form.py
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}

      - name: Detect recipe changes (without staging)
        id: check_changes
        run: |
          if git diff --quiet; then
            echo "No new recipes."
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "New recipes found."
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Run search_prep.py
        if: steps.check_changes.outputs.changed == 'true'
        run: python _tools/search_prep.py

      - name: Run update_indexes.py
        if: steps.check_changes.outputs.changed == 'true'
        run: python _tools/update_indexes.py

      - name: Create Pull Request
        if: steps.check_changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "📥 New recipes added!"
          branch: ${{ env.BRANCH_NAME }}
          base: main
          title: "📥 New recipes added"
          body: |
            This PR was auto-generated from new Google Form submissions.
            It includes:
            - New recipes in `recipes/`
            - Updated search data
            - Updated category/protein indexes
